services:
  tpf_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/api/src
  
  tpf_db:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpf
      MYSQL_USER: tpf
      MYSQL_PASSWORD: tpf
      MYSQL_TCP_PORT: 3307